version: '3.8'

services:
  frontend:
    build:
      context: ./hackathon  # Path to your Vite application directory
      dockerfile: Dockerfile  # Ensure the Dockerfile is named correctly
    ports:
      - "5179:5173"
    networks:
      - app-network
    environment:
      - VITE_API_URL_PROD=http://3.111.175.69:8011

  backend:
    build:
      context: ./backend  # Path to your Node.js application directory
      dockerfile: Dockerfile  # Ensure the Dockerfile is named correctly
    ports:
      - "8011:8000"
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb+srv://shrey:shrey@cluster0.bt3np.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

networks:
  app-network:  
    driver: bridge
