version: '3.8'

services:
  frontend:
    build:
      context: ./hackathon  # Path to your Vite application directory
      dockerfile: Dockerfile  # Ensure the Dockerfile is named correctly
    ports:
      - "3000:3000"  # Maps port 3000 in the container to 3000 on the host
    networks:
      - app-network
    # environment:
    #   - VITE_API_URL_STAGING=http://backend:8000  # Use backend service name in the network
    depends_on:
      - backend  # Ensure backend is ready before starting frontend

  backend:
    build:
      context: ./backend  # Path to your Node.js backend application directory
      dockerfile: Dockerfile  # Ensure the Dockerfile is named correctly
    ports:
      - "8011:8000"  # Expose port 8000 in the container as 8011 on the host
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb+srv://shrey:shrey@cluster0.bt3np.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

networks:
  app-network:  
    driver: bridge
