
name: ci/cd pipeline

on: 
  push: 
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    # needs: test-frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Build Docker images
        run: docker-compose build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > hackAi.pem
          chmod 600 hackAi.pem
      - name: Deploy to AWS EC2
        run: |
          ssh -i hackAi.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            
            
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            # Navigate to the project directory
            if [ ! -d "/home/ubuntu/hackathon/.git" ]; then
              git clone https://github.com/ShreySinha02/hackathon.git 
            else
              cd /home/ubuntu/hackathon
              git pull origin main
            fi
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
      - name: Clean Up SSH Key
        run: rm -f hackAi.pem
